# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseItems', '0003_auto_20180326_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='/img/periodico.jpg', max_length=10485760, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='new',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
