# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseItems', '0004_auto_20180328_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='/img/periodico.jpg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='new',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
