# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.BaseItems')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            bases=('myapp.baseitems',),
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('baseitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.BaseItems')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='/gymkana/miapp/image.jpg', upload_to='image/')),
            ],
            bases=('myapp.baseitems',),
        ),
    ]
