# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='/home/asuarez/gymk/image/image.jpg', upload_to='image/'),
        ),
    ]
