# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180521_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='/home/asuarez/gymkana-django/images/image.jpg', upload_to='images/'),
        ),
    ]
